# Cluster command
cluster: mkdir -p logs/{rule} errors/{rule} &&
  sbatch
  --partition={resources.partition}
  --qos={resources.qos}
  --cpus-per-task={threads}
  --mem={resources.mem_mb}
  --job-name={rule}-{wildcards}
  --output=logs/{rule}/%j.out
  --error=errors/{rule}/%j.error
  --time={resources.time}

# Default resources for all rules
default-resources:
  - partition=short
  - qos=normal
#  - mem_mb=2000
  - time="00:30:00"
set-resources:
    - run_aneufinder_qc:mem_mb=128000
max-jobs-per-second: 100
max-status-checks-per-second: 100
local-cores: 1
latency-wait: 60
jobs: 100

use-conda: true
conda-frontend: "mamba"
